#!/bin/bash
cd src/turbineModels/turbineModelsStandard
rmdepall
wclean
cd ../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver.ADM
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine.ADM
rmdepall
wclean
cd ../../../../../